### ISSUE TITLE
Macro-issue: milestone should be the same for macro and all sub-issues

### ISSUE THREAD

**Issue by giogonzo** [buildo/nemobot#89]
## requirements

the button already creates the sub-issues with the correct milestone,
but probably it makes sense to enforce this also later on,
when changing milestone to the macro issue

don't worry too much about "big" macros, we have the "split" functionality now!
## specs

{optional: describe technical specs to implement this feature, if not obvious}
## misc

{optional: other useful info}

**Comment by lucacioria** [comment]
@giogonzo can you give some rationale on this one? Don't you think it's a valid scenario to have sub-issues outside of the milestone? (I sincerely don't know).

@FrancescoCioria maybe you have some thoughts here?

**Comment by FrancescoCioria** [comment]
> Don't you think it's a valid scenario to have sub-issues outside of the milestone?

It happened to me a couple of times in the last weeks, but I think the right approach in those cases is to remove them from the macro issue for these reasons:
- in most cases these issues are minor/icebox or complicated (my personal experience)
  - icebox/minor -> move out of macro with label `icebox`. we don't want icebox sub-issues, it makes no sense in my opinion as **every** sub-issue must be completed in order to complete/close the macro (so they all have the same importance)
  - complicated -> this should ring a bell. IMO *correct* solutions in this case are
    - split in more sub-issues
    - split macro issues in multiple macro so to archive a part of it
    - simply leave macro issue open for longer than expected at the beginning (no one will die :) )
- avoid macro issue to remain open because of minor/icebox/complicated issues

**Comment by lucacioria** [comment]
great summary @FrancescoCioria I agree with your analysis..

in this case, I think the main objective here would be to find an easy way to move subissues to another macro issue (split functionality?)

**Comment by FrancescoCioria** [comment]
> I think the main objective here would be to find an easy way to move subissues to another macro issue (split functionality?)

It already exists! (but it's secret and not-documented :P)

**Comment by lucacioria** [comment]
ok! then let's open an issue to document and show it somewhere I guess.. or explain this to everybody before lunch one day :)

**Comment by giogonzo** [comment]
we don't use milestones anymore
